const images: string[] = [
    'bug.svg',
    'dark.svg',
    'dragon.svg',
    'electric.svg',
    'fairy.svg',
    'fighting.svg',
    'fire.svg',
    'flying.svg',
    'ghost.svg',
    'grass.svg',
    'ground.svg',
    'ice.svg',
    'normal.svg',
    'poison.svg',
    'psychic.svg',
    'rock.svg',
    'steel.svg',
    'water.svg',
];

